<?php
/**
 * Ars Nova Ticketing Bridge - one canonical page per concert.
 *
 * WHY THIS EXISTS
 * ---------------
 * Angela Raabe's comp ticket for the 12 September house concert (order 7858,
 * 2026-09-11) carried a link reading "View concert details ->". It pointed at
 * /tc-events/house-concert-with-nicolo-spera-sep-12/ - Tickera's generated
 * single-event page, which renders the tc_events post's OWN featured image (an
 * August draft) rather than the artwork carried by the concert page and by the
 * ticket product. A buyer clicking that link saw a different picture from the
 * one in the email she was reading.
 *
 * The link was not the disease. This site has TWO page systems for one concert:
 *
 *   /this-season/house-concert-september-2026/            page 6488
 *       designed: program notes, artist bio, the ticket block
 *   /tc-events/house-concert-with-nicolo-spera-sep-12/    post 6643
 *       generated by Tickera: title, stale image, a bare add-to-cart table
 *
 * and the generated one is PUBLIC, has an archive, and on 2026-09-11 had 23
 * URLs in the Yoast sitemap competing in search with the seven real concert
 * pages - five of them for Darkness & Light alone. Nobody chose that. tc_events
 * ships public and nothing ever turned it off.
 *
 * WHY THIS IS ONE FILTER AND NOT AN EMAIL EDIT
 * --------------------------------------------
 * Both bad links in that email come from the same call. includes/order-email-
 * details.php does get_permalink( $event_id ) for its "View concert details"
 * link, and Tickera's own TICKETS_TABLE does get_permalink() for the Event Name
 * cell. Patching the email template would have fixed one of the two and left
 * the other, and left every future caller wrong by default.
 *
 * So this changes what a tc_events permalink IS. post_type_link makes
 * get_permalink() return the concert page for every caller that exists now or
 * is written later; template_redirect 301s the raw URL for every ticket, email
 * and search result already in the wild.
 *
 * THE MAPPING ALREADY EXISTED
 * ---------------------------
 * event -> event_category term -> `ans_page_id` term meta -> page. That is the
 * same link includes/event-tickets-block.php walks in the OTHER direction so a
 * concert page can find its own performances. Nothing new is invented here; an
 * existing relationship is read backwards.
 *
 * WHAT DELIBERATELY DOES NOT REDIRECT
 * -----------------------------------
 * An event with no mapped page keeps its own URL and behaves exactly as it does
 * today. Event 7188 (Nova Circle Membership 2026/27) is the live case: a
 * season-long membership is not a performance and has no concert page, and
 * sending it somewhere plausible would be worse than leaving it alone. It is
 * noindexed instead - a duplicate that should not rank is a different problem
 * from a duplicate that should redirect.
 *
 * The editor's own permalink UI is also left alone. get_sample_permalink()
 * arrives here with $leavename or $sample set, and both are passed straight
 * through, so the slug field in wp-admin keeps telling the truth about the post
 * it is editing.
 *
 * THE SEQUENCING TRAP, recorded because it nearly shipped in the wrong order
 * ------------------------------------------------------------------------
 * A tc_events page is not always dead weight. On 2026-09-11 event 7843
 * (Crosscurrents - May 22, Livestream) had been created the previous day
 * without an event_category, so it appeared on NO concert page and its own
 * tc_events page was the ONLY surface from which its published, buyable $35
 * ticket could be reached. Shipping this redirect before adding that term would
 * have taken a live ticket off sale with nothing surfacing it. The term was
 * added to category 79 first, and only then was this enabled.
 *
 * Before enabling this for a new season, run
 * GET ars-nova/v1/tickera/event-canonical - it lists every published event and
 * whether it has a canonical page - and close the gaps first.
 *
 * @package ars-nova-ticketing-bridge
 * @since   1.22.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * The concert page an event belongs to.
 *
 * Walks the event's event_category terms and returns the first `ans_page_id`
 * that resolves to a PUBLISHED page. The published check matters: a term can
 * point at a page that has since been drafted, and redirecting the public to a
 * draft would be a 404 for everyone who is not logged in.
 *
 * @param int $event_id tc_events post ID.
 * @return int Page ID, or 0 when the event has no canonical page.
 */
function ans_tb_event_page_id( $event_id ) {
	$event_id = (int) $event_id;

	if ( ! $event_id ) {
		return 0;
	}

	static $cache = array();

	if ( array_key_exists( $event_id, $cache ) ) {
		return $cache[ $event_id ];
	}

	$cache[ $event_id ] = 0;

	if ( 'tc_events' !== get_post_type( $event_id ) ) {
		return 0;
	}

	$terms = wp_get_post_terms( $event_id, 'event_category', array( 'fields' => 'ids' ) );

	if ( is_wp_error( $terms ) || empty( $terms ) ) {
		return 0;
	}

	foreach ( $terms as $term_id ) {
		$page_id = ans_tb_term_page_id( $term_id );

		if ( $page_id ) {
			$cache[ $event_id ] = $page_id;
			break;
		}
	}

	return $cache[ $event_id ];
}

/**
 * The concert page an event_category term points at.
 *
 * @param int $term_id event_category term ID.
 * @return int Page ID, or 0.
 */
function ans_tb_term_page_id( $term_id ) {
	$page_id = (int) get_term_meta( (int) $term_id, 'ans_page_id', true );

	if ( ! $page_id ) {
		return 0;
	}

	$page = get_post( $page_id );

	if ( ! $page || 'page' !== $page->post_type || 'publish' !== $page->post_status ) {
		return 0;
	}

	return $page_id;
}

/**
 * Canonical public URL for an event.
 *
 * No recursion risk: the page is a `page`, whose permalink runs through
 * page_link / _get_page_link, not post_type_link.
 *
 * @param int $event_id tc_events post ID.
 * @return string URL, or '' when the event has no canonical page.
 */
function ans_tb_event_canonical_url( $event_id ) {
	$page_id = ans_tb_event_page_id( $event_id );

	if ( ! $page_id ) {
		return '';
	}

	$url = get_permalink( $page_id );

	return is_string( $url ) ? $url : '';
}

/**
 * Make get_permalink() on a tc_events post return its concert page.
 *
 * This is the whole fix for the email. Both the "View concert details" link in
 * includes/order-email-details.php and Tickera's own Event Name cell call
 * get_permalink(), so correcting the permalink corrects both, plus anything
 * written later that reasonably expects a link to an event to go somewhere a
 * human wants to land.
 *
 * @param string  $post_link  Permalink WordPress built.
 * @param WP_Post $post       The post.
 * @param bool    $leavename  Editor is asking for a %postname% template.
 * @param bool    $sample     Editor is asking for a sample permalink.
 * @return string
 */
function ans_tb_event_permalink( $post_link, $post, $leavename = false, $sample = false ) {
	if ( ! ( $post instanceof WP_Post ) || 'tc_events' !== $post->post_type ) {
		return $post_link;
	}

	// The slug field in wp-admin must keep describing the post it is editing.
	if ( $leavename || $sample ) {
		return $post_link;
	}

	$url = ans_tb_event_canonical_url( $post->ID );

	return $url ? $url : $post_link;
}
add_filter( 'post_type_link', 'ans_tb_event_permalink', 10, 4 );

/**
 * Send a raw tc_events or event_category URL to the concert page.
 *
 * Covers what the permalink filter cannot: links already printed on tickets, in
 * emails sent before this shipped, in Google's index, and in anyone's bookmarks.
 *
 * 301 rather than 302 on purpose - the duplicates need to be consolidated into
 * the concert pages in search, and a 302 does not do that. It is filterable for
 * the one situation that would otherwise mean a release: needing to soften it
 * while something is being diagnosed.
 *
 * `?ans_raw=1` lets anyone who can edit posts still inspect the generated page.
 *
 * @return void
 */
function ans_tb_event_canonical_redirect() {
	if ( is_admin() ) {
		return;
	}

	$status = (int) apply_filters( 'ans_tb_event_redirect_status', 301 );
	$url    = '';

	if ( is_post_type_archive( 'tc_events' ) ) {
		// The generated archive has no editorial purpose and never did.
		$season = (int) apply_filters( 'ans_tb_season_page_id', 256 );
		$url    = $season ? (string) get_permalink( $season ) : '';
	} elseif ( is_singular( 'tc_events' ) ) {
		if ( isset( $_GET['ans_raw'] ) && current_user_can( 'edit_posts' ) ) {
			return;
		}
		$url = ans_tb_event_canonical_url( get_queried_object_id() );
	} elseif ( is_tax( 'event_category' ) ) {
		// The same duplicate in taxonomy form, and the term is where
		// ans_page_id actually lives, so the mapping is even more direct.
		$term = get_queried_object();
		$url  = ( $term instanceof WP_Term ) ? (string) get_permalink( ans_tb_term_page_id( $term->term_id ) ) : '';
	}

	if ( '' === $url ) {
		return;
	}

	wp_safe_redirect( $url, $status );
	exit;
}
add_action( 'template_redirect', 'ans_tb_event_canonical_redirect' );

/**
 * Keep generated event pages out of the search index.
 *
 * Redundant for a mapped event - a 301 never renders a robots tag - and
 * load-bearing for an unmapped one, which still renders its own page.
 *
 * @param array $robots wp_robots directives.
 * @return array
 */
function ans_tb_event_robots( $robots ) {
	if ( is_singular( 'tc_events' ) || is_post_type_archive( 'tc_events' ) || is_tax( 'event_category' ) ) {
		unset( $robots['index'] );
		$robots['noindex'] = true;
		$robots['follow']  = true;
	}

	return $robots;
}
add_filter( 'wp_robots', 'ans_tb_event_robots' );

/**
 * Yoast prints its own robots tag and ignores wp_robots, so it is told twice.
 *
 * Both filter names are live in Yoast 28; hooking only one of them is the same
 * class of mistake as hooking one of tickera_apply_filters()'s three names.
 */
add_filter(
	'wpseo_robots',
	function ( $robots ) {
		return ans_tb_event_is_generated() ? 'noindex, follow' : $robots;
	}
);

add_filter(
	'wpseo_robots_array',
	function ( $robots ) {
		if ( ans_tb_event_is_generated() && is_array( $robots ) ) {
			$robots['index'] = 'noindex';
		}

		return $robots;
	}
);

/**
 * True on any Tickera-generated event view.
 *
 * @return bool
 */
function ans_tb_event_is_generated() {
	return is_singular( 'tc_events' ) || is_post_type_archive( 'tc_events' ) || is_tax( 'event_category' );
}

/**
 * Stop submitting generated pages to Google.
 *
 * tc_api_keys is in this list for a different reason and is not scope creep:
 * the 2026-09-11 sitemap index carried tc_api_keys-sitemap.xml, so Tickera's
 * API-key post type was being handed to search engines. It is infrastructure
 * and has no business in a sitemap at all.
 *
 * @param bool   $excluded  Current decision.
 * @param string $post_type Post type being considered.
 * @return bool
 */
add_filter(
	'wpseo_sitemap_exclude_post_type',
	function ( $excluded, $post_type ) {
		return in_array( $post_type, array( 'tc_events', 'tc_api_keys' ), true ) ? true : $excluded;
	},
	10,
	2
);

add_filter(
	'wpseo_sitemap_exclude_taxonomy',
	function ( $excluded, $taxonomy ) {
		return 'event_category' === $taxonomy ? true : $excluded;
	},
	10,
	2
);

/**
 * Report which published events do and do not have a canonical page.
 *
 * This exists because of event 7843 (see the header). The failure it catches is
 * silent by construction: an event with no category renders on no concert page,
 * so the only evidence is a page that is missing a row nobody is looking for.
 * Run this before enabling the redirect on a new season.
 *
 * GET /wp-json/ars-nova/v1/tickera/event-canonical
 *
 * @return array
 */
function ans_tb_event_canonical_report() {
	$events = get_posts(
		array(
			'post_type'   => 'tc_events',
			'post_status' => 'publish',
			'numberposts' => -1,
			'fields'      => 'ids',
		)
	);

	$rows    = array();
	$orphans = 0;

	foreach ( $events as $event_id ) {
		$page_id = ans_tb_event_page_id( $event_id );
		$terms   = wp_get_post_terms( $event_id, 'event_category', array( 'fields' => 'names' ) );

		if ( ! $page_id ) {
			$orphans++;
		}

		$rows[] = array(
			'id'         => (int) $event_id,
			'title'      => html_entity_decode( get_the_title( $event_id ), ENT_QUOTES, 'UTF-8' ),
			'kind'       => (string) get_post_meta( $event_id, 'ans_event_kind', true ),
			'categories' => is_wp_error( $terms ) ? array() : array_values( $terms ),
			'page_id'    => $page_id,
			'canonical'  => ans_tb_event_canonical_url( $event_id ),
			'redirects'  => (bool) $page_id,
		);
	}

	return array(
		'count'      => count( $rows ),
		'redirected' => count( $rows ) - $orphans,
		'orphans'    => $orphans,
		'events'     => $rows,
	);
}

add_action(
	'rest_api_init',
	function () {
		register_rest_route(
			'ars-nova/v1',
			'tickera/event-canonical',
			array(
				'methods'             => 'GET',
				'callback'            => 'ans_tb_event_canonical_report',
				'permission_callback' => function () {
					return current_user_can( 'manage_options' );
				},
			)
		);
	}
);
